# Autogenerated wrapper script for Qt5Location_jll for i686-linux-gnu-cxx11
export libqt5location, libqt5positioning, libqt5positioningquick

using Qt5Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt5Location")
JLLWrappers.@declare_library_product(libqt5location, "libQt5Location.so.5")
JLLWrappers.@declare_library_product(libqt5positioning, "libQt5Positioning.so.5")
JLLWrappers.@declare_library_product(libqt5positioningquick, "libQt5PositioningQuick.so.5")
function __init__()
    JLLWrappers.@generate_init_header(Qt5Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt5location,
        "lib/libQt5Location.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5positioning,
        "lib/libQt5Positioning.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt5positioningquick,
        "lib/libQt5PositioningQuick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
